#!/bin/bash

if [ -f main.py ]; then echo 'python3'; exit 0; fi
if [ -f main.py ]; then echo 'pygame'; exit 0; fi
if [ -f main.py ]; then echo 'pyxel'; exit 0; fi
if [ -f main.bal ]; then echo 'ballerina'; exit 0; fi
if [ -f main.sh ]; then echo 'bash'; exit 0; fi
if [ -f main.c ]; then echo 'c'; exit 0; fi
if [ -f main.lisp ]; then echo 'clisp'; exit 0; fi
if [ -f main.clj ]; then echo 'clojure'; exit 0; fi
if [ -f main.cpp ]; then echo 'cpp'; exit 0; fi
if [ -f main.cpp ]; then echo 'cpp11'; exit 0; fi
if [ -f main.cr ]; then echo 'crystal'; exit 0; fi
if [ -f main.cs ]; then echo 'csharp'; exit 0; fi
if [ -f main.dart ]; then echo 'dart'; exit 0; fi
if [ -f main.el ]; then echo 'elisp'; exit 0; fi
if [ -f main.exs ]; then echo 'elixir'; exit 0; fi
if [ -f main.erl ]; then echo 'erlang'; exit 0; fi
if [ -f src/index.js ]; then echo 'flow'; exit 0; fi
if [ -f main.fs ]; then echo 'forth'; exit 0; fi
if [ -f main.fs ]; then echo 'fsharp'; exit 0; fi
if [ -f src/pages/index.js ]; then echo 'gatsbyjs'; exit 0; fi
if [ -f main.go ]; then echo 'go'; exit 0; fi
if [ -f main.scm ]; then echo 'guile'; exit 0; fi
if [ -f main.hs ]; then echo 'haskell'; exit 0; fi
if [ -f Main.java ]; then echo 'java'; exit 0; fi
if [ -f config.json ]; then echo 'jest'; exit 0; fi
if [ -f main.jl ]; then echo 'julia'; exit 0; fi
if [ -f main.kt ]; then echo 'kotlin'; exit 0; fi
if [ -f main.lua ]; then echo 'love2d'; exit 0; fi
if [ -f main.lua ]; then echo 'lua'; exit 0; fi
if [ -f pages/index.js ]; then echo 'nextjs'; exit 0; fi
if [ -f main.nim ]; then echo 'nim'; exit 0; fi
if [ -f index.js ]; then echo 'nodejs'; exit 0; fi
if [ -f main.ml ]; then echo 'ocaml'; exit 0; fi
if [ -f main.pas ]; then echo 'pascal'; exit 0; fi
if [ -f main.php ]; then echo 'php'; exit 0; fi
if [ -f main.py ]; then echo 'python'; exit 0; fi
if [ -f main.quil ]; then echo 'quil'; exit 0; fi
if [ -f main.raku ]; then echo 'raku'; exit 0; fi
if [ -f index.js ]; then echo 'react_native'; exit 0; fi
if [ -f src/index.js ]; then echo 'reactjs'; exit 0; fi
if [ -f src/index.tsx ]; then echo 'reactts'; exit 0; fi
if [ -f main.r ]; then echo 'rlang'; exit 0; fi
if [ -f main.rb ]; then echo 'ruby'; exit 0; fi
if [ -f main.rs ]; then echo 'rust'; exit 0; fi
if [ -f Main.scala ]; then echo 'scala'; exit 0; fi
if [ -f main.sql ]; then echo 'sqlite'; exit 0; fi
if [ -f main.swift ]; then echo 'swift'; exit 0; fi
if [ -f main.tcl ]; then echo 'tcl'; exit 0; fi
if [ -f main.wat ]; then echo 'webassembly'; exit 0; fi
if [ -f index.js ]; then echo 'enzyme'; exit 0; fi
if [ -f index.js ]; then echo 'express'; exit 0; fi

if [ -n "$(find . -name '*.py')" ]; then echo 'python3'; exit 0; fi
if [ -n "$(find . -name '*.py')" ]; then echo 'pygame'; exit 0; fi
if [ -n "$(find . -name '*.py')" ]; then echo 'pyxel'; exit 0; fi
if [ -n "$(find . -name '*.bal')" ]; then echo 'ballerina'; exit 0; fi
if [ -n "$(find . -name '*.sh')" ]; then echo 'bash'; exit 0; fi
if [ -n "$(find . -name '*.c')" ]; then echo 'c'; exit 0; fi
if [ -n "$(find . -name '*.lisp')" ]; then echo 'clisp'; exit 0; fi
if [ -n "$(find . -name '*.clj')" ]; then echo 'clojure'; exit 0; fi
if [ -n "$(find . -name '*.cljc')" ]; then echo 'clojure'; exit 0; fi
if [ -n "$(find . -name '*.cljs')" ]; then echo 'clojure'; exit 0; fi
if [ -n "$(find . -name '*.edn')" ]; then echo 'clojure'; exit 0; fi
if [ -n "$(find . -name '*.cpp')" ]; then echo 'cpp'; exit 0; fi
if [ -n "$(find . -name '*.cpp')" ]; then echo 'cpp11'; exit 0; fi
if [ -n "$(find . -name '*.cr')" ]; then echo 'crystal'; exit 0; fi
if [ -n "$(find . -name '*.cs')" ]; then echo 'csharp'; exit 0; fi
if [ -n "$(find . -name '*.dart')" ]; then echo 'dart'; exit 0; fi
if [ -n "$(find . -name '*.el')" ]; then echo 'elisp'; exit 0; fi
if [ -n "$(find . -name '*.elc')" ]; then echo 'elisp'; exit 0; fi
if [ -n "$(find . -name '*.ex')" ]; then echo 'elixir'; exit 0; fi
if [ -n "$(find . -name '*.exs')" ]; then echo 'elixir'; exit 0; fi
if [ -n "$(find . -name '*.erl')" ]; then echo 'erlang'; exit 0; fi
if [ -n "$(find . -name '*.js')" ]; then echo 'flow'; exit 0; fi
if [ -n "$(find . -name '*.fs')" ]; then echo 'forth'; exit 0; fi
if [ -n "$(find . -name '*.fs')" ]; then echo 'fsharp'; exit 0; fi
if [ -n "$(find . -name '*.js')" ]; then echo 'gatsbyjs'; exit 0; fi
if [ -n "$(find . -name '*.go')" ]; then echo 'go'; exit 0; fi
if [ -n "$(find . -name '*.scm')" ]; then echo 'guile'; exit 0; fi
if [ -n "$(find . -name '*.hs')" ]; then echo 'haskell'; exit 0; fi
if [ -n "$(find . -name '*.java')" ]; then echo 'java'; exit 0; fi
if [ -n "$(find . -name '*.js')" ]; then echo 'jest'; exit 0; fi
if [ -n "$(find . -name '*.jl')" ]; then echo 'julia'; exit 0; fi
if [ -n "$(find . -name '*.kt')" ]; then echo 'kotlin'; exit 0; fi
if [ -n "$(find . -name '*.lua')" ]; then echo 'love2d'; exit 0; fi
if [ -n "$(find . -name '*.lua')" ]; then echo 'lua'; exit 0; fi
if [ -n "$(find . -name '*.js')" ]; then echo 'nextjs'; exit 0; fi
if [ -n "$(find . -name '*.nim')" ]; then echo 'nim'; exit 0; fi
if [ -n "$(find . -name '*.js')" ]; then echo 'nodejs'; exit 0; fi
if [ -n "$(find . -name '*.ml')" ]; then echo 'ocaml'; exit 0; fi
if [ -n "$(find . -name '*.pas')" ]; then echo 'pascal'; exit 0; fi
if [ -n "$(find . -name '*.pp')" ]; then echo 'pascal'; exit 0; fi
if [ -n "$(find . -name '*.php')" ]; then echo 'php'; exit 0; fi
if [ -n "$(find . -name '*.py')" ]; then echo 'python'; exit 0; fi
if [ -n "$(find . -name '*.quil')" ]; then echo 'quil'; exit 0; fi
if [ -n "$(find . -name '*.raku')" ]; then echo 'raku'; exit 0; fi
if [ -n "$(find . -name '*.js')" ]; then echo 'react_native'; exit 0; fi
if [ -n "$(find . -name '*.js')" ]; then echo 'reactjs'; exit 0; fi
if [ -n "$(find . -name '*.tsx')" ]; then echo 'reactts'; exit 0; fi
if [ -n "$(find . -name '*.r')" ]; then echo 'rlang'; exit 0; fi
if [ -n "$(find . -name '*.rb')" ]; then echo 'ruby'; exit 0; fi
if [ -n "$(find . -name '*.rs')" ]; then echo 'rust'; exit 0; fi
if [ -n "$(find . -name '*.scala')" ]; then echo 'scala'; exit 0; fi
if [ -n "$(find . -name '*.sql')" ]; then echo 'sqlite'; exit 0; fi
if [ -n "$(find . -name '*.swift')" ]; then echo 'swift'; exit 0; fi
if [ -n "$(find . -name '*.tcl')" ]; then echo 'tcl'; exit 0; fi
if [ -n "$(find . -name '*.wat')" ]; then echo 'webassembly'; exit 0; fi
if [ -n "$(find . -name '*.js')" ]; then echo 'enzyme'; exit 0; fi
if [ -n "$(find . -name '*.js')" ]; then echo 'express'; exit 0; fi
