sudo: required

services:
  - docker

env:
  - TEST=all
  - TEST=changed

before_install:
  # we need origin/master so we know what's changed in `make changed-test`
  - if [ $TEST == "changed" ]; then git remote set-branches --add origin master && git fetch; fi

script:
  - if [ $TEST == "all" ]; then make test -j$(nproc); fi
  - if [ $TEST == "changed" ]; then make changed-test -j$(nproc); fi
