name = "ballerina"
entrypoint = "main.bal"
languages = [
  "java"
]
extensions = [
  "bal"
]
setup = [
  "wget https://dist.ballerina.io/downloads/1.2.13/ballerina-linux-installer-x64-1.2.13.deb",
  "dpkg -i ballerina-linux-installer-x64-1.2.13.deb",
  "rm -r ballerina-linux-installer-x64-1.2.13.deb"
]


[run]
command = [
  "ballerina",
  "run",
  "main.bal"
]

[tests]

  [tests.hello]
  code = """
import ballerina/io;
public function main() {
    io:println("Hello, World!");
}
"""
  output = "Hello, World!\n"
