name = "common lisp"
entrypoint = "main.lisp"
aliases = [
  "lisp"
]
extensions = [
  "asd",
  "lisp"
]
packages = [
  "cl-quicklisp",
  "sbcl"
]
setup = [
  "sbcl --non-interactive --load /usr/share/cl-quicklisp/quicklisp.lisp --eval '(quicklisp-quickstart:install)' --eval '(ql-util:without-prompting (ql:add-to-init-file))'"
]

[run]
command = [
  "sbcl",
  "--script",
  "./main.lisp"
]

[tests]

  [tests.hello]
  code = "(format t \"Hello, world!\")"
  output = "Hello, world!"
