name = "cpp11"
languages = [
  "c"
]
entrypoint = "main.cpp"
extensions = [
  "cpp",
  "cc",
]

[compile]
command = [
  "clang++-10",
  "-pthread",
  "-std=c++11",
  "-o",
  "main"
]

[run]
command = [
  "./main"
]

[tests]

  [tests.hello]
  code = "#include <iostream>\nint main() { std::cout << \"hello\" << std::endl; }"
  output = "hello\n"

[languageServer]
command = [
  "cquery",
  "--init={\"progressReportFrequencyMs\": -1,\"cacheDirectory\":\"/tmp/cquery\", \"extraClangArguments\": [\"-std=c++11\", \"-pthread\"]}"
]
