name = "elixir"
languages = [
  "erlang"
]
entrypoint = "main.exs"
extensions = [
  "ex",
  "exs"
]
packages = [
  "elixir",
]

[run]
command = [
  "elixir",
  "./main.exs"
]

[tests]

  [tests.hello]
  code = "IO.puts \"hello world\""
  output = "hello world\n"
