name = "erlang"
entrypoint = "main.erl"
extensions = [
  "erl"
]
aptKeyUrls = [
  "https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc"
]
aptRepos = [
  "deb https://packages.erlang-solutions.com/ubuntu bionic contrib"
]
packages = [
  "esl-erlang"
]

versionCommand = [
  "erl",
  "-version"
]

[compile]
command = [
  "erlc",
  "main.erl"
]

[run]
command = [
  "erl",
  "-noshell",
  "-s",
  "main",
  "start",
  "-s",
  "init",
  "stop"
]

[tests]

  [tests.hello]
  code = "-module(main).\n-export([start/0]).\n\nstart() ->\n  io:fwrite(\"hello world\n\")."
  output = "hello world\n"
