name = "express"
entrypoint = "index.js"
extensions = [
  "js"
]
popularity = 1.0

[run]
command = [
  "node",
  "index.js"
]

[tests]

  [tests.hello]
  code = "console.log(\"hello\")"
  output = "hello\n"
