name = "fsharp"
languages = [
  "csharp"
]
aliases = [
  "f#"
]
entrypoint = "main.fs"
extensions = [
  "fs"
]

packages = [
  "fsharp",
]

[compile]
command = [
  "fsharpc",
  "--nologo",
  "--out:main.exe"
]

[run]
command = [
  "mono",
  "main.exe"
]

[tests]

  [tests.hello]
  code = "System.Console.WriteLine(\"hello\")"
  output = "hello\n"
