name = "go"
aliases = [
  "golang"
]
entrypoint = "main.go"
extensions = [
  "go"
]
aptRepos = [
  "ppa:longsleep/golang-backports"
]

packages = [
  "golang-1.14-go=1.14.2-1longsleep1+bionic",
  "pkg-config"
]
setup = [
  "go get -u github.com/saibing/bingo"
]

[compile]
command = [
  "go",
  "build",
  "-o",
  "main"
]

[run]
command = [
  "./main"
]

[tests]

  [tests.hello]
  code = "package main \nimport \"fmt\" \nfunc main() { \nfmt.Println(\"hello\") \n}"
  output = "hello\n"

[languageServer]
command = [
  "/bin/bash",
  "-c",
  "/opt/homes/go/go/bin/bingo"
]
