name = "go"
aliases = [
  "golang"
]
entrypoint = "main.go"
extensions = [
  "go"
]

packages = [
  "pkg-config"
]
setup = [
  "cd /tmp && wget -q https://golang.org/dl/go1.14.7.linux-amd64.tar.gz && tar -C /usr/local -xzf go1.14.7.linux-amd64.tar.gz && rm go1.14.7.linux-amd64.tar.gz",
  "/usr/local/go/bin/go get -u github.com/saibing/bingo"
]

[compile]
command = [
  "go",
  "build",
  "-o",
  "main"
]

[run]
command = [
  "./main"
]

[tests]

  [tests.hello]
  code = "package main \nimport \"fmt\" \nfunc main() { \nfmt.Println(\"hello\") \n}"
  output = "hello\n"

  [tests.version]
  code = "package main \nimport (\"fmt\" \n\"runtime\") \nfunc main(){fmt.Print(runtime.Version()[:7])}"
  output = "go1.14."

[languageServer]
command = [
  "/bin/bash",
  "-c",
  "/opt/homes/go/go/bin/bingo"
]
