name = "jest"
entrypoint = "config.json"
extensions = [
  "js"
]
packages = []
setup = [
  "yarn global add jest"
]

[run]
pty = false
command = [
  "jest",
  "--colors",
  "--config",
  "/home/runner/config.json"
]