name = "nextjs"
entrypoint = "pages/index.js"
extensions = [
  "js"
]
packages = []
setup = [
  "npm install -g prettier@1.13.4",
  "mkdir -p /hom/runner/pages",
  "yarn install"
]

[run]
pty = false
command = [
  "yarn",
  "dev"
]