name = "night"
entrypoint = "main.night"
extensions = [
  "night"
]
packages = [
  "unzip",
  "wget"
]
setup = [
  "cd /tmp",
  "wget -q https://repl.it/@TheForArkLD/Night.zip",
  "unzip -q -o Night.zip \"night\"",
  "cp -f night /usr/bin/night",
  "chmod +x /usr/bin/night"
]

[run]
command = [
  "night"
]

[tests]
  
  [tests.hello]
  code = "print \"hello\\n\";"
  output = "hello\n"
