name = "nim"
entrypoint = "main.nim"
extensions = [
  "nim"
]

setup = [
  "cd /tmp && wget --quiet http://releases.llvm.org/6.0.0/clang+llvm-6.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz && tar xf clang+llvm-6.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz && cp clang+llvm-6.0.0-x86_64-linux-gnu-ubuntu-16.04/bin/clang-format /bin/ && rm -rf clang+llvm-6.0.0-x86_64-linux-gnu-ubuntu-16.04 && rm -rf clang+llvm-6.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz"
]

packages = [
  "nim"
]

[run]
pty = true
command = [
  "nim",
  "compile",
  "--run",
  "main.nim"
]

[tests]

  [tests.hello]
  code = "echo \"hello world\""
  output = "CC: main\nCC: stdlib_system\nhello world\n"
