name = "perl6"
entrypoint = "main.p6"
extensions = [
  "p6"
]
packages = [
  "libssl-dev"
]
setup = [
  "apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 379CE192D401AB61",
  'echo "deb https://dl.bintray.com/nxadm/rakudo-pkg-debs `lsb_release -cs` main" | tee -a /etc/apt/sources.list.d/rakudo-pkg.list',
  "apt-get update && apt-get install rakudo-pkg",
  "ln -s /opt/rakudo-pkg/bin/perl6 /usr/local/bin/perl6",
  "ln -s /opt/rakudo-pkg/bin/zef /usr/local/bin/zef",
  "zef install Linenoise"
]


[run]
pty = true
command = [
  "perl6",
  "./main.p6"
]

[tests]

  [tests.hello]
  code = "say 'hello world';"
  output = "hello world\n"
