name = "pygame"
entrypoint = "main.py"
extensions = [
  "py"
]
languages = [
  "python3"
]
packages = [
  "gcc",
  "libsdl-ttf2.0-dev",
  "libevent-dev",
  "libportmidi-dev",
  "libsdl1.2-dev",
  "libsdl-image1.2-dev",
  "libsdl-mixer1.2-dev",
  "libtk8.6",
  "xfonts-base",
  "xfonts-100dpi",
  "xfonts-75dpi",
  "xfonts-cyrillic",
  "fontconfig",
  "fonts-freefont-ttf",
  "libfreetype6-dev",
]
popularity = 5.0
setup = [
  "/opt/virtualenvs/python3/bin/python3 -m pip install pygame",
  # Avoid using older versions of the typing library.
  "/opt/virtualenvs/python3/bin/python3 -m pip uninstall -y typing",
]
[run]
command = [
  "python3",
  "-B",
  "main.py"
]

[tests]

  [tests.0]
  code = "print(__name__)"
  output = "__main__\n"

  [tests.hello]
  code = "print(\"hello\")"
  output = "hello\n"

[languageServer]
command = [
  "pyls",
  "-v"
]
