name = "quil"
languages = [
  "python3"
]
entrypoint = "main.quil"
extensions = [
  "quil"
]
packages = []
setup = [
  "/opt/virtualenvs/python3/bin/pip3 install referenceqvm==0.3 pyquil==1.9.0",
  # Avoid using older versions of the typing library.
  "/opt/virtualenvs/python3/bin/python3 -m pip uninstall -y typing",
]

versionCommand = [
  "/bin/bash",
  "-c",
  "/opt/virtualenvs/python3/bin/pip3 show pyquil | grep Version "
]
