name = "rails"
entrypoint = "config/routes.rb"
extensions = [
  "rb"
]
packages = [
  "libxslt-dev",
  "libxml2-dev",
  "build-essential",
  "patch",
  "ruby-dev",
  "zlib1g-dev",
  "pkg-config",
  "sqlite3",
  "libsqlite3-dev",
  "liblzma-dev"
]
setup = [
  "chown -R runner:runner /usr/local/bundle",
  "chown -R runner:runner /home/runner"
]

[run]
pty = true
command = [
  "bash",
  "-c",
  "rails db:migrate && rails server --binding 0.0.0.0 --port 3000"
]