name = "reactts"
languages = [
  "nodejs"
]
entrypoint = "src/index.tsx"
extensions = [
  "tsx"
]
setup = [
  "rm -rf /home/runner/.profile /home/runner/.bashrc /home/runner/.bash_logout /home/runner/.cache /home/runner/.npm",
  "npx create-react-app --scripts-version=react-scripts-ts /home/runner/app",
  "rsync --archive /home/runner/app/ /home/runner",
  "rm -rf /home/runner/app",
  "yarn",
  "rm -f README.md"
]

[run]
command = [
  "yarn",
  "start"
]
