name = "ruby"
entrypoint = "main.rb"
extensions = [
  "rb"
]
packages = [
  "build-essential",
  "rake-compiler",
  "ruby-dev",
  "ruby",
  "rubygems-integration",
  "rubygems",
  "libsqlite3-dev",
]
setup = [
  """
  # Gemfile.lock files are dependent on the exact bundler version. Always add
  # new versions and never remove old versions from this list.
  gem install bundler:2.2.3 bundler:2.2.7
  gem install --source http://rubygems.org rspec:3.5 stripe rufo:0.12.0 sinatra
  gem install solargraph:0.38.1
  /usr/bin/build-prybar-lang.sh ruby
  """
]

[run]
command = [
  "ruby",
  "main.rb"
]

[tests]

  [tests.hello]
  code = "puts \"hello\""
  output = "hello\n"

[languageServer]
command = [
  "solargraph",
  "stdio"
]
